version: '3.1'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx:1.0.1
        container_name: nginx
        networks:
            - my-network
        ports:
            - 80:80
    flask:
        build:
            context: ./flask
            dockerfile: Dockerfile
        image: flask:1.0.0
        container_name: flask
        ports:
            - 8000:8000
        networks:
            my-network:
                aliases:
                    - flask-api
networks:
    my-network: